Assignment no 8

1. Write Python Programs to use various operators in Python


Arithmatic operator:

In [1]:
# Addition
num1 = 10
num2 = 5
result = num1 + num2
print("Addition:", result)

# Subtraction
result = num1 - num2
print("Subtraction:", result)

# Multiplication
result = num1 * num2
print("Multiplication:", result)

# Division
result = num1 / num2
print("Division:", result)

# Modulus
result = num1 % num2
print("Modulus:", result)

# Exponentiation
result = num1 ** num2
print("Exponentiation:", result)

# Floor Division
result = num1 // num2
print("Floor Division:", result)


Addition: 15
Subtraction: 5
Multiplication: 50
Division: 2.0
Modulus: 0
Exponentiation: 100000
Floor Division: 2


Comparison Operators:

In [2]:
num1 = 10
num2 = 5

# Equal to
print("Equal to:", num1 == num2)

# Not equal to
print("Not equal to:", num1 != num2)

# Greater than
print("Greater than:", num1 > num2)

# Less than
print("Less than:", num1 < num2)

# Greater than or equal to
print("Greater than or equal to:", num1 >= num2)

# Less than or equal to
print("Less than or equal to:", num1 <= num2)


Equal to: False
Not equal to: True
Greater than: True
Less than: False
Greater than or equal to: True
Less than or equal to: False


Logical Operators:

In [3]:
num1 = 10
num2 = 5

# AND operator
print("AND operator:", num1 > 0 and num2 > 0)

# OR operator
print("OR operator:", num1 > 0 or num2 > 0)

# NOT operator
print("NOT operator:", not(num1 > 0))


AND operator: True
OR operator: True
NOT operator: False


Assignment Operators:

In [4]:
num = 10

# Addition assignment
num += 5
print("Addition assignment:", num)

# Subtraction assignment
num -= 3
print("Subtraction assignment:", num)

# Multiplication assignment
num *= 2
print("Multiplication assignment:", num)

# Division assignment
num /= 4
print("Division assignment:", num)

# Modulus assignment
num %= 3
print("Modulus assignment:", num)

# Exponentiation assignment
num **= 2
print("Exponentiation assignment:", num)

# Floor division assignment
num //= 2
print("Floor division assignment:", num)


Addition assignment: 15
Subtraction assignment: 12
Multiplication assignment: 24
Division assignment: 6.0
Modulus assignment: 0.0
Exponentiation assignment: 0.0
Floor division assignment: 0.0


2. Create list of elements and slice and dice it

In [5]:
# Create a list of elements
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Slice the list to get a subset
subset = my_list[2:7]
print("Subset:", subset)  # Output: [3, 4, 5, 6, 7]

# Slice the list to get every second element
every_second = my_list[::2]
print("Every Second Element:", every_second)  # Output: [1, 3, 5, 7, 9]

# Reverse the list
reversed_list = my_list[::-1]
print("Reversed List:", reversed_list)  # Output: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


Subset: [3, 4, 5, 6, 7]
Every Second Element: [1, 3, 5, 7, 9]
Reversed List: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


3. Using while loop accept numbers until sum of numbers is less than 100

In [6]:
total = 0

while total < 100:
    num = int(input("Enter a number: "))
    total += num

print("Sum of numbers is:", total)


Enter a number: 50
Enter a number: 50
Sum of numbers is: 100


4. Write a python program Read & write Excel files 

In [ ]:
import pandas as pd

# Read Excel file
data = pd.read_excel("file path")

# Print the contents of the Excel file
print(data)

import pandas as pd

# Create a DataFrame
data = {
    'Name': ['John', 'Jane', 'Mike'],
    'Age': [25, 30, 35],
    'City': ['New York', 'London', 'Paris']
}

df = pd.DataFrame(data)

# Write DataFrame to Excel file
df.to_excel('output.xlsx', index=False)




5. Write a python program to scrape reviews from a commercial web site

In [15]:
import requests
from bs4 import BeautifulSoup

# Define the URL of the webpage containing the reviews
url = 'https://www.example.com/reviews'

# Send a GET request to the webpage
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the HTML content of the webpage
    soup = BeautifulSoup(response.content, 'html.parser')

    # Find the elements containing the reviews
    review_elements = soup.find_all('div', class_='review')

    # Extract and print the reviews
    for review in review_elements:
        review_text = review.text.strip()
        print(review_text)
else:
    print('Failed to retrieve the webpage. Status code:', response.status_code)


Failed to retrieve the webpage. Status code: 404


6. Create a 3x3 matrix with values ranging from 2 to 10 using numpy

In [16]:
import numpy as np

# Create a 1D array with values ranging from 2 to 10
arr = np.arange(2, 11)

# Reshape the 1D array into a 3x3 matrix
matrix = np.reshape(arr, (3, 3))

# Print the matrix
print(matrix)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


7. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array

In [17]:
import numpy as np

# List of numeric values
my_list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
my_array = np.array(my_list)

# Print the array
print(my_array)


[1 2 3 4 5]


8. "Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [18]:
import numpy as np

# Create a null vector of size 10
null_vector = np.zeros(10)

# Update the sixth value to 11
null_vector[5] = 11

# Print the updated null vector
print(null_vector)


[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]
